// Even Fibonacci Numbers
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
*/

namespace Problems.Even_Fibonacci_Numbers;

public class Sum_Of_Even_Terms
{
    public List<int> sequence = new List<int> {1, 2};

    public void UpTo4million()
    {
        int i = 2;
        while (sequence[sequence.Count - 1] < 4000000 && sequence[i - 1] + sequence[i - 2] < 4000000 )
        {
            sequence.Add(sequence[i - 1] + sequence[i - 2]);
            i++; 
        }
    }

    public int SumOfEven()
    {
        int sum = 0;
        foreach (int item in sequence)
        {
            if (item % 2 == 0)
            {
                sum += item;
            }
        }
        return sum;
    }
}